menu:
- {name: 'home', url: '/'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/jyhaw'}
- {icon: 'linkedin', link: '#'}

contacts:
- {name: 'Dr. Jing Yan Haw', title: 'Senior Research Fellow', department: 'Centre for Quantum Technologies', institution: 'National University of Singapore', institution_address: 'Singapore', phone: '+65 9658 0496', email: 'jy.haw@nus.edu.sg', office: '', image: 'assets/img/contact.jpg'}
